apiVersion: v1
kind: ReplicationController
metadata:
  name: my-rc
  labels:
    app: my-app
spec:
  template:
    metadata:
      labels: 
        app: my-app
    spec:
      containers:
        - name: my-container
          image: httpd
          ports:
            - containerPort: 80
  
  selector:
    app: my-app

  replicas: 3

  