apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-rs
  labels:
    app: demo-app
spec:
  template:
    metadata:
      labels: 
        app: demo-app
    spec:
      containers:
        - name: demo-container
          image: httpd
          ports:
            - containerPort: 80

  replicas: 3

  selector:
    # matchLabels:
    #   app: demo-app
    
    matchExpression:
      - {key: app, operator: In, values: [demo-app]}

