apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cbz-ingress
  labels:
    app: cbz-ingress
spec: 
  ingressClassName: nginx
  defaultBackend:
    service:
      name: auth-app-service
      port:
        number: 80
  rules:
    - host: "cloth.cbz.com"
      http:
        paths:
          - pathType: prefix
            path: "/"
            backend:
              service:
                name: cloth-app-service
                port:
                  number: 80
    - host: "payment.cbz.com"
      http:
        paths:
          - pathType: prefix
            path: "/"
            backend:
              service:
                name: payment-app-service
                port:
                  number: 8080