apiVersion: apps/v1
kind: Deployment
metadata:
  name: studentapp
  labels:
    app: studentapp
spec:
  template:
    metadata:
      labels: 
        app: studentapp
    spec:
      containers:
        - name: studentapp-container
          image: shubhamkalsait1/studentapp-backend:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 400m
              memory: 400Mi

  replicas: 3

  selector:
    matchLabels:
      app: studentapp
  
  strategy:
    type: RollingUpdate