apiVersion: apps/v1
kind: Deployment
metadata:
  name: studentapp
  labels:
    app: studentapp
spec:
  template:
    metadata:
      labels: 
        app: studentapp
    spec:
      containers:
        - name: studentapp-container
          image: tomcat:8
          ports:
            - containerPort: 8080
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          request:
            cpu: 400m
            memoty: 400Mi

  replicas: 3

  selector:
    matchLabels:
      app: studentapp
  
  strategy:
    type: RollingUpdate