apiVersion: v1
kind: Service
metadata:
  name: studentapp-service
spec:
  ports:
  - targetPort: 8080
    port: 8080
    protocol: TCP
    name: java
  selector:
    app: studentapp
  type: LoadBalancer